name: docker-github-actions
on: 
  push:
    branches:
      - feature-1

jobs:
  docker-compose-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Check Docker version
        run: docker --version 

      - name: Check docker-compose 
        run: docker-compose --version  

      - name: Build and Run Docker Compose
        run: docker-compose up -d 

      - name: Stop Containers
        run: docker-compose down 
