name: CI/CD Pipeline

on:
  push:
    branches:
      - feature-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: adurikedharnadh/weather-app
          ref: feature-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Container
        run: |
          docker-compose -f docker-compose.yml up -d
